[package]
name = "ispc-downsampler"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "MIT/Apache-2.0"
description = "Image downsampler crate using ISPC"
documentation = "https://docs.rs/ispc-downsampler"
homepage = "https://github.com/Traverse-Research/ispc-downsampler"
repository = "https://github.com/Traverse-Research/ispc-downsampler"
include = [
    "/src/",
    "/benches/",
    "/examples/",
    "/README.md",
    "/LICENSE-*",
]

[dependencies]
ispc_rt = "1.1"

[build-dependencies]
ispc_compile = { version = "1.1", optional = true }
ispc_rt = "1.1"

[dev-dependencies]
image = "0.24.1"
stb_image = "0.2.4"
criterion = "0.3"
resize = "0.7"

[[bench]]
name = "basic"
harness = false

[features]
ispc = ["ispc_compile"]
