[package]
name = "ispc-downsampler"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "MIT/Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ispc_rt = "1.0.7"

[build-dependencies]
ispc_compile = { version = "1.0.4", optional = true }
ispc_rt = "1.0.7"

[dev-dependencies]
image = "0.24.1"
stb_image = "0.2.4"

[features]
ispc = ["ispc_compile"]
