#[allow(non_camel_case_types,dead_code,non_upper_case_globals,non_snake_case,improper_ctypes)]
pub mod downsample_ispc {
/* automatically generated by rust-bindgen 0.61.0 */

extern "C" {
    pub fn resample(
        width: u32,
        height: u32,
        stride: u32,
        num_channels: u8,
        target_width: u32,
        target_height: u32,
        src_data: *const u8,
        out_data: *mut u8,
    );
}
}